### ISSUE TITLE
🐛 Temporary Passwords

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#15]
I haven't been able to replicate, but both @erik-ilyin and @binarybottle have reported not getting temporary passwords when requesting them from https://api.mindlogger.info/#?dialog=resetpassword / the app / the admin panel.

**Comment by shnizzedy** [comment]
> api.mindlogger.info

**Comment by WorldImpex** [comment]
@binarybottle Can you still not receive temporary passwords?

**Comment by WorldImpex** [comment]
I can confirm on prod that I did not receive an email to my inbox or spam to reset my password

**Comment by shnizzedy** [comment]
I suspect [greylisting](https://en.wikipedia.org/wiki/Greylisting) but was never able to confirm.

**Comment by WorldImpex** [comment]
On the second attempt today to reset the password, I received the email but the link does not work. I opened a separate ticket for that [#683](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/683)

**Comment by sergeysemenuta** [comment]
Works as expected on the dev server
![2020-05-25_18-33-16.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/6c514be3-facc-413a-b194-a2971f35a727)
