### ISSUE TITLE
sign up on android up doesn't work

### ISSUE THREAD

**Issue by satra** [ChildMindInstitute/MindLogger-bug-reports#23]
when you get to the sign up page and fill in all the information and hit sign up, it blinks for a second and then nothing happens.

**Comment by shnizzedy** [comment]
Neither @henryrossiter nor I could replicate this issue. @satra, can we get some more details?

- MindLogger version?
- Were you online?
- Android version?

**Comment by satra** [comment]
i downloaded and tried again, same thing:

mindlogger version - 0.5.14
online - yes
android - 9 security patch level aug 1 2019 

i can try to demonstrate online if anyone would like to see it in action.

**Comment by shnizzedy** [comment]
Which database are you trying to create a user in (what endpoint are you connecting to)?

**Comment by satra** [comment]
i just downloaded and clicked on new user. i was not trying to follow any instructions anywhere else.

**Comment by shnizzedy** [comment]
What URL shows if you click the ![database glyph](https://user-images.githubusercontent.com/5974438/64035898-e05b1100-cb1f-11e9-8c7f-19ddb992eb1f.png) on the login screen?

**Comment by satra** [comment]
https://api.mindlogger.org/api/v1

**Comment by satra** [comment]
@shnizzedy - any thoughts or additional reports? is there a new version i should try?

**Comment by satra** [comment]
relatedly is there a way we can test mindlogger (automatically) across versions of android and create a dashboard?

**Comment by satra** [comment]
the current symptom is it does not crash, the sign up button just blinks :)

the crash piece was fixed in a prior update.

**Comment by sergeysemenuta** [comment]
Checked on the devices Xiaomi Mi 8 // Android 8.1.0; Sony G8232 Xperia XZS // Android 7.1.1
The issue is not reproducible.
MindLogger version: 0.11.4

**Comment by satra** [comment]
@sergeysemenuta - is that version of mindlogger available on the play store?

the version that is currently on the play store still has the same issue that i originally posted. i'm running android 9

**Comment by shnizzedy** [comment]
The beta release on Play is 9 versions behind the alpha release: 
![Play versions](https://user-images.githubusercontent.com/5974438/76101599-af5f0b80-5f9c-11ea-938e-2fcb1b082136.png)

**Comment by sergeysemenuta** [comment]
Rechecked on the  Redmi Note 8 Pro // Android 9
MindLogger version: 0.11.4
The issue is reproducible on this device
Video: https://www.dropbox.com/s/pmghd4oeac12wof/MOV_0038.mp4?dl=0

**Comment by henryrossiter** [comment]
@satra @sergeysemenuta 

I am able to reproduce this behavior when I try to create an account with a username or an email that is already associated with an account. Is there any chance you were using a username or email that you had already used for a separate account?

I am improving the form validation now to make the UI better but if you are confident that you were using unused usernames and emails there may be an underlying problem.

**Comment by satra** [comment]
@henryrossiter - if you can delete my account from the db, i can try to see if it works?

**Comment by sergeysemenuta** [comment]
Rechecked on the
 Redmi Note 8 Pro // Android 10 // v 0.11.21 
 Huawei P20 // Android 8.1.0 // v 0.11.21 
I was not able to replicate the issue.

**Comment by WorldImpex** [comment]
Fixed per @satra
