### ISSUE TITLE
🐛 Graphs override scrolling behavior

### ISSUE THREAD

**Issue by odziem** [ChildMindInstitute/MindLogger-bug-reports#28]
**Description**
It looks like D3 graphs are taking over the press / scroll event on the data page for an applet. Scrolling on text or the calendar area works, while scrolling on the graphs does not.

**To Reproduce**
1. Go to HBN data page.
2. Press and scroll on header area around "Morning"
3. Press and scroll on bar graph underneath header

**Screenshots**
![scroll2](https://user-images.githubusercontent.com/1141312/64868948-54141800-d60e-11e9-9f08-1172d2dbcfe7.gif)

**Smartphone:**
 - Device: OnePlus 6T
 - OS: Android 9

and

 - Device: Pixel 2 XL (simulator)
 - OS: Android 9

**Comment by binarybottle** [comment]
I don't see this behavior anymore on either Android or iOS, so I am closing this issue.
