### ISSUE TITLE
💡 Should we constrain applets so that, per database, names cannot be duplicated?

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#30]
Since we've made the design choice that anyone can create an applet from an existing activity set, it follows that multiple applets will exist for some activity sets (this is in fact already the case). This structure has caused persistent confusion, both with users and within the team. I wonder if constraining applet names would resolve this confusion.

[![](https://api.gh-polls.com/poll/01DP19ZPNH2VBJHX9EW2R5RN6J/Allow%20multiple%20applets%20to%20have%20the%20same%20name%20(status%20quo))](https://api.gh-polls.com/poll/01DP19ZPNH2VBJHX9EW2R5RN6J/Allow%20multiple%20applets%20to%20have%20the%20same%20name%20(status%20quo)/vote)
[![](https://api.gh-polls.com/poll/01DP19ZPNH2VBJHX9EW2R5RN6J/Constrain%20applets%20to%20one%20name%20per%20database)](https://api.gh-polls.com/poll/01DP19ZPNH2VBJHX9EW2R5RN6J/Constrain%20applets%20to%20one%20name%20per%20database/vote)
[![](https://api.gh-polls.com/poll/01DP19ZPNH2VBJHX9EW2R5RN6J/Other)](https://api.gh-polls.com/poll/01DP19ZPNH2VBJHX9EW2R5RN6J/Other/vote)

**Comment by shnizzedy** [comment]
/polls "Allow multiple applets to have the same name (status quo)" "Constrain applets to one name per activity set" "Other"

**Comment by satra** [comment]
@shnizzedy - i thought activity-sets and applets were synonymous? but indeed one can create as many of them.

**Comment by shnizzedy** [comment]
@satra that's part of the confusion! Applets take an activity set (currently de facto constrained to one activity set per applet) and add things like users and schedules which are not part of the activity set.

**Comment by satra** [comment]
@shnizzedy - thanks for that clarification

**Comment by binarybottle** [comment]
I take it then that the decision is to constrain the naming of applets within a given database to be unique.

**Comment by shnizzedy** [comment]
I don't think we've made a decision unless by,

> I take it then that the decision is to constrain the naming of applets within a given database to be unique,

you're saying that we are making that decision.

Since I'm getting questions like

> Could you please invite [people] to install the HBN EMA applet?

I think the gap between the imagination and reality of how MindLogger works is still wide enough that it needs to be addressed, but I'm not confident this suggestion will sufficiently close that gap.

**Comment by shnizzedy** [comment]
# Resolved

We shall constrain applets so that, per database, names cannot be duplicated.
