### ISSUE TITLE
✨📚📅 Define schedule formats

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#39]
**Is your feature request related to a problem? Please describe.**
We don't 

>  I don't have a good grasp of the format of stored scheduling data

― https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/204#issuecomment-548123955

> The dayspan-vuetify calendar library doesn't support Vuetify 2. We should eventually find a new calendar component so we can update Vuetify.

― https://github.com/ChildMindInstitute/mindlogger-admin/issues/19

**Describe the solution you'd like**
As @henryrossiter suggested, we should define our requirements and choose and design components based on those requirements.

**Describe alternatives you've considered**
To date, we've chosen components (here specifically [dayspan-veutify@0.4.0](https://npm.taobao.org/package/dayspan-vuetify/v/0.4.0)) and worked around their formats.

**Additional context**
Current relevant endpoints include:

### [`GET /schedule`](https://dev.mindlogger.org/api/v1#!/schedule/schedule_getSchedule)

> Get schedule Array for the logged-in user
> 
> Parameter | Description | Parameter Type | Data Type
> -------------- |  --------------- | --------------------- | --------------
> timezone |  The TZ database name of the timezone to return times in. Times returned in UTC if omitted. | query | string

#### Response Body
```json
{
  "applet/5d6ee74a8f66701eb8166011": {
    "activity/5db9bac59f43a2fb26fdf425": {
      "lastResponse": "2019-10-28T16:46:09.281000"
    }
  },
  "applet/5db71b412611b7876bb7a220": {
    "activity/5db9bba49f43a2fb26fdf484": {
      "lastResponse": null
    },
    "activity/5db9bba59f43a2fb26fdf485": {
      "lastResponse": null
    }
  }
}
```

### [`PUT /applet/{id}/constraints`](https://dev.mindlogger.org/api/v1#!/applet/applet_setConstraints)

> Set or update schedule information for an activity.
> 
> Parameter | Description | Parameter Type | Data Type
> -------------- | --------------- | --------------------- | -------------- 
> **id** | **The ID of the document.** | path | string
> activity | Girder ID (or Array thereof) of the activity/activities to schedule. | query | string
> schedule | A JSON object containing schedule information for an activity | formData | string

**Related**
- https://github.com/ChildMindInstitute/mindlogger-admin/issues/19
- #37 
- https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/204
- https://github.com/ChildMindInstitute/mindlogger-app/issues/276
- [MATTER Lab spec docs: MindLogger use case: NIMH ecological momentary assessment: Scheduling](https://childmindinstitute.github.io/MATTER-spec-docs/MindLogger/NIMH-EMA.html#scheduling)

**Comment by shnizzedy** [comment]
I think rather than a freeform JSON Object as a single `schedule` parameter, it would be useful to constrain the shape and contents of the schedule, either by specifying how that Object should exist or by passing different keys separately.

**Comment by binarybottle** [comment]
Can anyone think of what the advantages would be of having a freeform json object as a schedule parameter?

**Comment by curtpw** [comment]
I can start prototyping an implementation that uses the Veutify v2 calendar component instead of dayspan-vuetify BUT I would simply be attempting as close to a one-for-one replacement as possible. I'm not in a position to make strategic schema or architectural decisions since I only starting looking at this a couple of days ago. It is worth mentioning that scheduling seems to be the most complex and fragile aspect of the ML Admin Panel web app. Rewriting it a week or two before launch is not ideal. I'm trying to take a measure twice cut once approach.

**Comment by shnizzedy** [comment]
@curtpw, in standup yesterday, @henryrossiter suggested we better define what we're trying to do, I added on that we should do so in writing, and @odziem added that our back-and-forth on https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/204 was a useful iterative design-and-documentation thread. This issue is intended to _be_ the measuring twice you mentioned. Updating the calendar component is a [separate, related issue](https://github.com/ChildMindInstitute/mindlogger-admin/issues/19).

**Comment by shnizzedy** [comment]
> Can anyone think of what the advantages would be of having a freeform json object as a schedule parameter?

@binarybottle ― advantages to whom? The question is a classic balancing act between structure and flexibility. In this case, as far as I can tell, the advantages to a freeform JSON Object are:

beneficiary | advantage | cost
--- | --- | ---
developer, manager, coordinator, user | time to launch | stability, reliability, meeting expectations, control
manager, coordinator, user | extreme flexibility | nonfunctional / unimplemented functionality
developer, user support | setting schedule should rarely throw exceptions | silent failures, unknown / unknowable user requirements, pain points

To be clear, I think a freeform JSON Object (what we have now) is better than nothing (what we had before) but worse than a well-defined structure.

**Comment by shnizzedy** [comment]
related: https://github.com/ReproNim/reproschema/issues/46

**Comment by shnizzedy** [comment]
In this morning's standup, @odziem, @binarybottle, @henryrossiter, @hotavocado, and I discussed how to handle timezones.

* For now, we're sticking with timezone-encoded [dayspan](https://github.com/ClickerMonkey/dayspan) Objects.
* We'll eventually need to allow editors / managers / coordinators / users to specify whether specific schedules are timezone sensitive (eg, sleep times, safety check-ins) or absolute (eg, insulin injections).
* I vote for someday migrating to [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time)-encoded timestamps and storing a [tz database timezone](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) string like [pytz's recommendation](http://pytz.sourceforge.net/#localized-times-and-date-arithmetic)

**Comment by shnizzedy** [comment]
Here are some in-use-at-the-moment snippets to help until we document what we want:

https://github.com/ChildMindInstitute/mindlogger-admin/blob/97ed9fd8d9f41969c04934ee5314ae6bdbc1b256/src/Components/Utils/api/api.vue#L22-L29

https://github.com/ChildMindInstitute/mindlogger-admin/blob/1d136a8b4ee0448a23862b6085d638493af41c35/src/Steps/SetSchedule.vue#L143-L168

https://github.com/ChildMindInstitute/mindlogger-admin/blob/f0681f7319db526d317324962def6b4547ab8907/src/State/state.js#L35-L47

https://github.com/ChildMindInstitute/mindlogger-app/blob/33e5511d750eed23bc9fd77ee6cf86b85dcf2e85/app/state/applets/applets.selectors.js#L12-L104

https://github.com/ChildMindInstitute/mindlogger-app/blob/b54df9db872d2ba8f308cb772de211eff8ce282b/app/services/pushNotifications.js#L38-L97

https://github.com/ChildMindInstitute/mindlogger-app/blob/26061c7fa06e747125e24f0020f9333b447c8002/app/services/pushNotifications.js#L39-L98

https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/76abb94e8214449e1bf19e6fd3718e603631b15f/girderformindlogger/api/v1/applet.py#L425-L438

**Comment by shnizzedy** [comment]
For applet `5e1f4f47720011229c1a15d2` on [https://api.mindlogger.org/api/v1](5e1f4f47720011229c1a15d2), [my attempt to manually set a schedule](https://matter-lab.slack.com/archives/GRXQ6B5U2/p1579120281051800?thread_ts=1579110060.042400&cid=GRXQ6B5U2) ⅓ worked. I realized https://github.com/ChildMindInstitute/mindlogger-admin/issues/71 may have been the issue with it working; I think the schedule page on admin was saving the incorrect activity keys. I've updated to match the URLs of the activities actually contained in the applet. For the sake of documentation, here's what is currently set, which I intend to reflect the following schedule:

| activity | scheduled time | [notified](https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/68) if not completed time | 
| --- | --- | --- |
| EMA Assessment (Morning) | daily, 8:00 AM | 9:00 AM |
| EMA Assessment (Mid Day) | daily, 2:00 PM | 3:00 PM |
| EMA Assessment (Night) | daily, 7:00 PM | 8:00 PM |

```json
{
	"around": 1578805200000,
	"events": [{
			"data": {
				"URI": "https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH2/master/activities/morning_set/morning_set_schema",
				"busy": true,
				"calendar": "",
				"color": "#F44336",
				"description": "",
				"forecolor": "#ffffff",
				"icon": "",
				"location": "",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "09:00"
				}],
				"title": "EMA Assessment (Morning)",
				"useNotifications": true
			},
			"schedule": {
				"times": [
					"08"
				]
			}
		},
		{
			"data": {
				"URI": "https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH2/master/activities/day_set/day_set_schema",
				"busy": true,
				"calendar": "",
				"color": "#1976d2",
				"description": "",
				"forecolor": "#ffffff",
				"icon": "",
				"location": "",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "15:00"
				}],
				"title": "EMA Assessment (Mid Day)",
				"useNotifications": true
			},
			"schedule": {
				"times": [
					"14"
				]
			}
		},
		{
			"data": {
				"URI": "https://raw.githubusercontent.com/hotavocado/HBN_EMA_NIMH2/master/activities/evening_set/evening_set_schema",
				"busy": true,
				"calendar": "",
				"color": "#1976d2",
				"description": "",
				"forecolor": "#ffffff",
				"icon": "",
				"location": "",
				"notifications": [{
					"end": null,
					"notifyIfIncomplete": true,
					"random": false,
					"start": "20:00"
				}],
				"title": "EMA Assessment (Night)",
				"useNotifications": true
			},
			"schedule": {
				"times": [
					"19"
				]
			}
		}
	],
	"eventsOutside": true,
	"fill": false,
	"listTimes": true,
	"minimumSize": 0,
	"repeatCovers": true,
	"size": 1,
	"type": 1,
	"updateColumns": true,
	"updateRows": true
}
```

**Comment by WorldImpex** [comment]
Moved to #737
