### ISSUE TITLE
✨ Clarify invitation language

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#45]
**Additional context**
Ideally, we'd do #16 and store all of this text in language-tagged Objects in the database, but time constraints have negated that possibility for now. The method that currently assembles that HTML is [`Invitation().htmlInvitation`](https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/7820cb4b2414bd6c8841858948a91803c7039ae2/girderformindlogger/models/invitation.py#L180).

In the sample invitation below, the sources of the text are highlighted as follows:
* red: hardcoded into the `htmlInvitation` method
* green: loaded from the applet's schema documents
* yellow: loaded from elsewhere in the database

![highlighted example invitation](https://user-images.githubusercontent.com/5974438/69266023-5b204f00-0b98-11ea-92d3-40ec2802ca73.png)

The yellow sections, in sequence:
1. If the invitation includes a `displayName`, say "Arno", the invitation starts with that name, eg. "Arno, you have been…". Otherwise, the invitation starts with a captial-y "You have been…".
2. The name and email address of the coordinator or manager who created the invitation.
3. The name of the database serving the applet.
4. The name and email address of each reviewer for the applet.
5. The name and email address of each manager for the applet.
6. The name and email address of each coordinator for the applet.
7. The link to access the invitation on MindLoggger web.

All of the markup is included in the `htmlInvitation` method.

**Comment by shnizzedy** [comment]
Related https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/43

**Comment by binarybottle** [comment]
@shnizzedy -- where in the database would {greeting} be stored?  That's the part I wanted to look at.

**Comment by shnizzedy** [comment]
@binarybottle when an invitation is created, a `displayName` can be included. If one is, 
> the invitation starts with that name, eg. "Arno, you have been…". Otherwise, the invitation starts with a captial-y "You have been…".

― https://github.com/ChildMindInstitute/MindLogger-bug-reports/issues/45#issue-525989920

`greeting` is just a kwarg for the `str.format` method that checks for a `displayName` in the invitation and conditionally includes before "ou have been" either (`true`) that name, a comma, and a 'y' or (`false`) a 'Y':

https://github.com/ChildMindInstitute/mindlogger-app-backend/blob/7820cb4b2414bd6c8841858948a91803c7039ae2/girderformindlogger/models/invitation.py#L301-L303

**Comment by shnizzedy** [comment]
Invitations are created with [`POST /applet/{id}/invite`](https://dev.mindlogger.org/api/v1#!/applet/applet_invite)

**Comment by binarybottle** [comment]
Okay, so I could simply add some text preceding this, for example: "Welcome!  "

**Comment by binarybottle** [comment]
I just added a PR (#239) to update some of the text.

I recommend adding space above "Description" and making it boldface in:

> Welcome Arno; you have been invited by Jon (jon.clucas@childmind.org) to Healthy Brain Network self-report internal test on MindLogger.
> Description
>

**Comment by shnizzedy** [comment]
:point_up_2: @henryrossiter
