### ISSUE TITLE
✨ 📈 Visualize User Responses for Reviewers

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#61]
As a reviewer, I want to view user data in the admin panel so that I can gather synthesize data about the user. 

Requirements
- Provide a dashboard that allows the reviewer to filter by applet name, activity name and user's first name, last name and MRN number. 
- The users are displayed by the MRN number on the screen to reviewers 
- The admin can hoover over the MRN number to display the user's First and Last name 
- Once a reviewer has filtered to an activity, the user should be able to review results for each item in that activity 
    - The reviewer should now be able to filter by item name and question 
    - The reviewer should be able to filter by input type which will bring all of the items up that have the same item type 
- The review can view an item by itself to see the change in answer over time 
    - Allow the reviewer to hide specific answers out of a group of responses in an item to look at specific responses recorded 

[![Viewer panel in Figma](https://user-images.githubusercontent.com/5974438/50796040-439ce800-129e-11e9-896d-409c37b76095.png)](https://www.figma.com/file/cchWwbmGc7uZwIAzRfxHEJhx/Mindlogger-Admin-Panel?node-id=2%3A197)

I think a3546cb is where the original version was disabled and that the branch [`originalMaster`](https://github.com/ChildMindInstitute/mindlogger-app-admin-panel/tree/originalMaster) has the old code therein.

**Comment by WorldImpex** [comment]
We need to display the data to a reviewer on web for TokenLogger.  

Requirements 
1. Data visualization should be filterable: 
   1st: User or users 
   2nd: Applet
   3rd: Activity 
2. Filter results by date range 
3. Downloadable (PDF) 
4. See each item results within an activity

**Comment by WorldImpex** [comment]
completed in https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/272

- PDF issue created separately #641
