### ISSUE TITLE
Download applets intelligently

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#62]
* Current the app will download all applets (including activities, screens, etc) every time the user presses refresh or opens the app
* Ideally it would not download applets unless the applet had not been downloaded before, or some "modified" date was newer than the one in app memory

**Comment by Eden2016** [comment]
The app uses [redux-persist](https://github.com/rt2zz/redux-persist) to cache the app state. So if the user has closed the app, on new enter they will see the stored data and appropriate API call will be fired to update that data in the background. In my opinion, it is not necessary to store the data additionally, besides redux-persist.
