### ISSUE TITLE
✨🔪 Make Applets in User's Applet Array Severable

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#66]
**Is your feature request related to a problem? Please describe.**
If a user has more than one applet and any of those applets is unrenderable, none of the user's applets will display (in the mobile app at least). I'm almost certain that this current functionality was the cause of https://github.com/ChildMindInstitute/mindlogger-app/issues/317.

**Describe the solution you'd like**
For a given Array of applets, if some applets are renderable and some are unrenderable, the subset of renderable applets should be rendered as if that was the full set of applets.

**Comment by binarybottle** [comment]
@InheritxSolution -- Please review
