### ISSUE TITLE
📚 Clarify Documentation About Notifications

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#68]
- [ ] specify that we're using local notifications as opposed to remote notifications
- [ ] clarify how notifications are populated and when this information is updated (related https://github.com/ChildMindInstitute/mindlogger-app/issues/319)

Ref ["Push technology: Push notification," *Wikipedia*](https://en.wikipedia.org/wiki/Push_technology#Push_notification), ["Framework: UserNotifications," _Apple Developer_](https://developer.apple.com/documentation/usernotifications)

**Comment by shnizzedy** [comment]
Related: https://github.com/ChildMindInstitute/mindlogger-app/issues/330

**Comment by binarybottle** [comment]
@shnizzedy -- Where would it be best to document this?  In the website, code, and spec docs?

**Comment by shnizzedy** [comment]
> Where would it be best to document this? In the website, code, and spec docs?

Any to all of those places.

For the website, I think users would just need to know what notifications will happen offline and which need the internet.

For the code, we should be clear about what we're doing.

For the specs, we should be clear about what we're intending to do.

**Comment by shnizzedy** [comment]
Oh, also in the various issues about notifications: 

- https://github.com/ChildMindInstitute/mindlogger-admin/issues/72
- https://github.com/ChildMindInstitute/mindlogger-app/issues/310
- https://github.com/ChildMindInstitute/mindlogger-app/issues/327
- https://github.com/ChildMindInstitute/mindlogger-app/issues/328
- https://github.com/ChildMindInstitute/mindlogger-app/issues/623

**Comment by WorldImpex** [comment]
Event: An activity that has a specific start time in a day. 
General schedule: A group of events created for a particular applet. 
Notification: A message that is sent to the user's device at a predetermined time 

Requirements: 
* Allow the manager or coordinator to set a time that a notification is sent to the user for an activity within an applet 
* Allow the manager or coordinator to set as many notifications as required for same or different times on any day on the same activity event or multiple
* Allow the manager or coordinator to set a reoccurring daily or weekly notification 
* A random notification is set by the manager or coordinator entering the start time and end time. The notification will then fire randomly between this time frame 
* When the user clicks on the notification it should drop the user on the first question of that activity
