### ISSUE TITLE
🐛🤖 "Unfortunately, MindLogger has stopped"

### ISSUE THREAD

**Issue by shnizzedy** [ChildMindInstitute/MindLogger-bug-reports#69]
Submitter: Marco Samson
Email: marco.samson21@gmail.com
When trying to login to the Mindlogger app on Android device after an account creation it's immediately crashed with the following popup msg: "Unfortunately, MindLogger has stopped."

**Comment by shnizzedy** [comment]
From crash log:

```
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)
libjsc.so
```

Looks like we need to upgrade React Native (we're currently using 0.59.9, and this bug is in versions 0.59.10 and older): https://github.com/facebook/react-native/issues/25494

**Comment by binarybottle** [comment]
@shnizzedy on Slack: "I don't know how many devices this will affect or how big of a job it'd be to update the required packages to avoid breaking version conflicts."

**Comment by WorldImpex** [comment]
react-native updated
