### ISSUE TITLE
Clicking on data icon crashes ML 🐛 [User-reported Bug]

### ISSUE THREAD

**Issue by satra** [ChildMindInstitute/MindLogger-bug-reports#78]
**Describe the bug**
I have just registered and not done a survey yet. Clicking on the greyed out data icon crashes mindlogger.

**To Reproduce**
1. Login into mindlogger on android (i'm on android 9)
2. Click on the data icon in the bottom (wait 5 seconds)

**Expected behavior**
ML should not crash

**Smartphone (please complete the following information):**
 - Device: Moto x4
 - OS: Android 
 - Version 9

**Comment by sergeysemenuta** [comment]
The issue is notreproduced on Huawei P20 // Android 9.0 // v 0.11.35 
Video: https://www.dropbox.com/s/hvv9rzrqgl30vaj/20200518_185243.mp4?dl=0
