### ISSUE TITLE
[Investigate] Git Bug Report is Broken 

### ISSUE THREAD

**Issue by devbtech** [ChildMindInstitute/MindLogger-bug-reports#96]
Git bug report stopped work so please investigate why it is broken and advise how much it will take to fix 

https://gitreports.com/issue/ChildMindInstitute/MindLogger-bug-reports

**Comment by WorldImpex** [comment]
There isn't free software out there right now that supports a bug report for gitrepo. We need to setup for the newest PM software

**Comment by WorldImpex** [comment]
replaced by clickup
